/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.7.0/samples
 */

plugins {
  id("java")
  id("com.gradleup.shadow") version "9.6.1"
}

group = "com.ryushin"
version = "1.0.2+HOTFIX"

repositories {
  mavenCentral()
  maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
  compileOnly("io.papermc.paper:paper-api:26.2.build.+")
  implementation("org.xerial:sqlite-jdbc:3.47.1.0")
}

java {
  toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

tasks {
  shadowJar {
    archiveClassifier.set("")
    relocate("org.sqlite", "com.ryushin.marriage.libs.sqlite")
  }
  build {
    dependsOn(shadowJar)
  }
}
