name: Marriage-Plugin
version: 1.0.1
main: com.ryushin.marriage.MarriagePlugin
author: Ryushin
description: Plugin pernikahan simpel dan ringan
api-version: 1.21
commands:
  marry:
    description: Menikah dengan pemain
  family:
    description: Mengelola relasi keluarga
