name: Marriage-Plugin
version: '1.0.0'
authors: "Ryushin"
website: "https://github.com/Sahur01-arch/Marriage-Plugin/"
main: com.ryushin.marriage.MarriagePlugin
api-version: 1.21
commands:
  marry:
    description: Menikah dengan pemain
  family:
    description: Mengelola relasi keluarga
